name: App-Commander - Release build

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  
  release_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Builds the release application.
        run: |
          ./gradlew clean package

      - name: Archive release applications.
        uses: actions/upload-artifact@v4
        if: success() || failure() # always run even if the previous step fails
        with:
          name: releases
          path: |
            **/build/compose/binaries/main/app/**
            **/build/compose/binaries/main/dmg/**
            **/build/libs/composeApp-jvm.jar
